apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spring-boot-docker-deployment
  labels:
    app: spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-docker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - image: hojin19082/restful_back:latest
        name: restful_back
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      nodeSelector:
        hostname: 10.105.7.102
