apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: comfy-ingress
    namespace: test
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: comfy.com
    http:
      paths:
        - path: /
          backend:
            serviceName: spring-boot-docker-service
            servicePort: 80