apiVersion: v1
kind: Service
metadata:
  labels: spring-boot-docker
  name: spring-boot-docker-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-boot-docker
  type: NodePort