apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker-service
spec:
  ports:
    - name: "8080"
      port: 8081
      targetPort: 8080
  selector:
    app: spring-boot-docker
  type: NodePort