apiVersion: v1
kind: Service
metadata:
  name: nginx-react-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-react
  type: LoadBalancer
