apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.commfy.shop"
    nginx.ingress.kubernetes.io/cors-allow-headers: "accesstoken,refreshtoken,withcredentials"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
spec:
  rules:
  - http:
      paths:
      - path: /auth
        pathType: ImplementationSpecific
        backend:
          service:
            name: msa-auth-service
            port: 
              number: 80
